use sde2b_works;

show tables;

CREATE TABLE RESERVATION_TB (
  RECORDID VARCHAR(12) PRIMARY KEY,
  CUSTOMERNAME VARCHAR(40) NOT NULL,
  BOOKINGTYPE VARCHAR(30) NOT NULL,
  BOOKING_DATE DATE NOT NULL,
  CONFIRMATIONNO VARCHAR(20),
  AMOUNT INT,
  REMARKS VARCHAR(100)
);


alter table reservation_tb modify RECORDID int auto_increment; 
